/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  basicSidebar: [
    {
      type: "autogenerated",
      dirName: "basic",
    },
  ],
  HTMLSidebar: [
    {
      type: "autogenerated",
      dirName: "HTML",
    },
  ],
  CSSSidebar: [
    {
      type: "autogenerated",
      dirName: "CSS",
    },
  ],
  JavaScriptSidebar: [
    {
      type: "autogenerated",
      dirName: "JavaScript",
    },
  ],
  VueSidebar: [
    {
      type: "autogenerated",
      dirName: "Vue",
    },
  ],
  FastAPISidebar: [
    {
      type: "autogenerated",
      dirName: "FastAPI",
    },
  ],
  MySQLSidebar: [
    {
      type: "autogenerated",
      dirName: "MySQL",
    },
  ],
  gitSidebar: [
    {
      type: "autogenerated",
      dirName: "git",
    },
  ],
  DockerSidebar: [
    {
      type: "autogenerated",
      dirName: "Docker",
    },
  ],
  deploySidebar: [
    {
      type: "autogenerated",
      dirName: "deploy",
    },
  ],
  todoListSidebar: [
    {
      type: "autogenerated",
      dirName: "todolist",
    },
  ],
  mallSidebar: [
    {
      type: "autogenerated",
      dirName: "mall",
    },
  ],
  systemDesignSidebar: [
    {
      type: "autogenerated",
      dirName: "SystemDesign",
    },
  ],
  noteSidebar: [
    {
      type: "autogenerated",
      dirName: "notes",
    },
  ],
};

module.exports = sidebars;
