/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  basicSidebar: [
    {
      type: "autogenerated",
      dirName: "basic",
    },
  ],
  frontendSidebar: [
    {
      type: "autogenerated",
      dirName: "frontend",
    },
  ],
  backendSidebar: [
    {
      type: "autogenerated",
      dirName: "backend",
    },
  ],
  gitSidebar: [
    {
      type: "autogenerated",
      dirName: "git",
    },
  ],
  devopsSidebar: [
    {
      type: "autogenerated",
      dirName: "devops",
    },
  ],
  todoSidebar: [
    {
      type: "autogenerated",
      dirName: "todo",
    },
  ],
  projectSidebar: [
    {
      type: "autogenerated",
      dirName: "project",
    },
  ],
  systemDesignSidebar: [
    {
      type: "autogenerated",
      dirName: "SystemDesign",
    },
  ],
  noteSidebar: [
    {
      type: "autogenerated",
      dirName: "notes",
    },
  ],
};

module.exports = sidebars;
